function [order_of_keypoints, one_side_joints] = getKeypointOrderInCSV(detector)
% Temp
one_side_joints = {"Shoulder", "Elbow", "Wrist", "Eye", "Hip", "Knee", "Ankle", "Ear"};
if strcmp(detector, "alphapose_new") % new version of alphapose (lakeside)
    order_of_keypoints = {'Nose', 'Neck', ...
        'RShoulder', 'RElbow', 'RWrist', ...
        'LShoulder', 'LElbow', 'LWrist', ...
        'MidHip', 'RHip', 'RKnee', 'RAnkle', ...
        'LHip', 'LKnee', 'LAnkle', ...
        'REye', 'LEye', 'REar', 'LEar', ...
        'LFootBall', 'LToe', 'LHeel', ...
        'RFootBall', 'RToe', 'RHeel'}; 
    % Note that for the 25pt openpose model there are extra available points on the feet (https://i.stack.imgur.com/lEaX4.png)
elseif strcmp(detector, "openpose")
    % Openpose has different ordering: https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md
    order_of_keypoints = {'Nose', 'Neck', ...
        'RShoulder', 'RElbow', 'RWrist', ...
        'LShoulder', 'LElbow', 'LWrist', ...
        'MidHip', 'RHip', 'RKnee', 'RAnkle', ...
        'LHip', 'LKnee', 'LAnkle', ...
        'REye', 'LEye', 'REar', 'LEar'}; % Note that for the 25pt openpose model there are extra available points on the feet (https://i.stack.imgur.com/lEaX4.png)
elseif strcmp(detector, 'romp') || strcmp(detector, 'openpose25')
    order_of_keypoints = {'Nose', 'Neck', ...
        'RShoulder', 'RElbow', 'RWrist', ...
        'LShoulder', 'LElbow', 'LWrist', ...
        'MidHip', 'RHip', 'RKnee', 'RAnkle', ...
        'LHip', 'LKnee', 'LAnkle', ...
        'REye', 'LEye', 'REar', 'LEar', ...
        'LToe', 'LFootBall', 'LHeel', 'RToe', 'RFootBall', 'RHeel'};    
        one_side_joints = {"Shoulder", "Elbow", "Wrist", "Eye", "Hip", "Knee", "Ankle", "Ear", "Toe", "FootBall", "Heel"};
elseif strcmp(detector, 'detectron') || strcmp(detector, 'alphapose') % old version of alphapose
    % COCO style keypoints: https://github.com/facebookresearch/Detectron/blob/master/detectron/utils/keypoints.py
    order_of_keypoints = {'Nose', 'LEye', 'REye', 'LEar', ...
        'REar', 'LShoulder', 'RShoulder', 'LElbow', ...
        'RElbow', 'LWrist', 'RWrist', 'LHip', ...
        'RHip', 'LKnee', 'RKnee', 'LAnkle', ...
        'RAnkle'};
end

end

